### ISSUE TITLE
Error al generar el zip con "npm run zip"

### ISSUE THREAD

**Issue by jperezdelafuente** [practicas-ging/mooc_node-mod2_cmd_iterators#1]
Al generar el zip con "npm run zip" me muestra el siguiente error que indica que no encuentra el modulo 'archiver':

```
> mooc_node-mod2_cmd_iterators@ zip D:\javascript\Modulo2.Arrays,Multi-Asignación,SpreadRest,Iteradores\mooc_node-mo­d2_cmd_iterators
> node tests/compress.js

module.js:549
throw err;
^

Error: Cannot find module 'archiver'
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (D:\javascript\Modulo2.Arrays,Multi-Asignación,SpreadRest,Iteradores\mooc_node-m­od2_cmd_iterators\tests\compress.js:3:18)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mooc_node-mod2_cmd_iterators@ zip: `node tests/compress.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mooc_node-mod2_cmd_iterators@ zip script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by jperezdelafuente** [comment]
Se corrige lanzando previamente: "npm install archiver"

**Comment by jperezdelafuente** [comment]
El archivo package.json debería contener la dependencia archiver
